### ISSUE TITLE
Window contents are scaled highly

### ISSUE THREAD

**Issue by DaveTacker** [Airblader/i3#121]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.13-50-ga98717d (2017-01-03, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-50-ga98717d (2017-01-03, branch "gaps-next") (pid 1836)
Loaded i3 config: /home/dave/.i3/config (Last modified: Fri 06 Jan 2017 09:53:43 PM HST, 1290 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5751530024075264.bz2

**What I did:**

Rebooting and logging back in the scale of the windows are all very high. Text within some windows is correct (like gedit) but Chrome and Thunar have LARGE contents.

**What I saw:**

[![Screenshots.png](https://s24.postimg.org/9zxp07w6d/Screenshots.png)](https://postimg.org/image/qnp72pqxt/)

**What I expected instead:**

Something great. =)

**Comment by Airblader** [comment]
The window manager is not responsible for what happens inside the window. This seems like a DPI issue, so I suggest reading the ArchWiki article on HiDPI.

**Comment by DaveTacker** [comment]
Even with the size of the i3 bar being so large? I read the [ArchWiki article on HiDPI](https://wiki.archlinux.org/index.php/HiDPI) and tried the suggested workaround assigning DPI manually as listed [Display_size_and_DPI](https://wiki.archlinux.org/index.php/Xorg#Display_size_and_DPI).

I've added `exec xrandr --dpi 127.34` to the i3 config as well as adding it to the .xsessionrc file in my $HOME directory. Neither have reverted the problem to a pre-reboot state. Any other advice?

**Comment by Airblader** [comment]
> Even with the size of the i3 bar being so large?

i3bar is not i3. Again, the window manager has no knowledge of what happens inside a window (and it has no reason to care). To the window manager, a window is just a black box rectangle with some abstract properties.

> as well as adding it to the .xsessionrc

That seems like a bad idea because `exec` in a shell has a completely different meaning from `exec` in i3. No commands after that in your `.xsessionrc` will run anymore with this.

> Any other advice?

Don't forget about `Xft:dpi` in your `~/.Xresources` (and make sure the Xresources are loaded).

Personally my approach to DPI is pragmatic. I run my machine with a »wrong« DPI of 96. It works for me.

**Comment by DaveTacker** [comment]
*Thanks for [helping me](https://www.reddit.com/r/unixporn/comments/5mju81/issues_with_i3_everything_is_very_large/dc47b4s/) with this airblader!*
# Solution
Specifying DPI to ~/.Xresources:
```
Xft.dpi: 96
```
and to ~/.xinitrc
```
xrandr --dpi 96
```
[![Screenshots.png](http://i.imgur.com/LNnuIbz.png)](http://i.imgur.com/LNnuIbz.png)
