### ISSUE TITLE
i3bar tray icon transparent and i3status issue

### ISSUE THREAD

**Issue by heelsleeh** [Airblader/i3#128]
Output of `i3 --moreversion 2>&- || i3 --version`:
**Running i3 version: 4.13-101-g88fbb6b**
_REPLACE: i3 version output_

URL to a logfile as per http://i3wm.org/docs/debugging.html:

_REPLACE: URL to logfile_

**What I did:**
1. this is my conky config (JOSON)
]
{
    "full_text": "  ${time %Y-%m-%d %H:%M %A }",
    "color": "\#cccccc",
    "border": "\#222222",
    ${template0},
    "separator": false,
    "separator_block_width": 3
}
],
_REPLACE: e.g. "I’m pressing Alt+j (focus left)"_

**What I saw:**
issue 1.
 **i3bar tray ,transparent config #00000070, here is i3bar show**
![heelsleeh-2017-02-20-13 42 15](https://cloud.githubusercontent.com/assets/24011272/23113331/6a76f28e-f772-11e6-8bb8-59d22439a142.png)

issue 2.
**i3status border bad display ,here is i3 with i3bar looks like**
![heelsleeh-2017-02-20-13 20 04](https://cloud.githubusercontent.com/assets/24011272/23113402/ce176288-f772-11e6-8b6e-b92858096e56.png)
**and here is i3-gap with i3bar look like** 
![heelsleeh-2017-02-20-13 28 16](https://cloud.githubusercontent.com/assets/24011272/23113435/0cc49b4a-f773-11e6-8239-b25a991cc82a.png)

**thanks for the great work:)**

_REPLACE: e.g. "i3 changed focus to the window ABOVE the current window"_

**What I expected instead:**
_REPLACE: e.g. "Focus should be on the window to the left"_

**Comment by Airblader** [comment]
The first issue is something I cannot reasonably change, see README. As for the border issue around the blocks… I cannot reproduce this.

Your issue is lacking a lot of information. The version you gave certainly isn't the full output the command gives, I'm pretty sure that conky config isn't complete and you're missing the i3 config entirely. Please provide all of this information.
