### ISSUE TITLE
Feature Request: Change bindsym based on active monitor

### ISSUE THREAD

**Issue by drgnomage** [Airblader/i3#131]
This stems from a fundamental issue of needing more than 10 workspaces on my work computer. I have generated up to 20 but the bindsym for moving a workspace to another workspace ends up being mod1+mod4+shift+number for me, which could be reduced to the regular bindsym if it was aware of the active monitor instead of needing an additional modifier. Otherwise I can assign to the function keys but this can interfere with other keybindings I have so I prefer not to.

My apologies if this feature is already present but I was unable to find it when looking through the documentation or other peoples examples.

**Comment by Airblader** [comment]
This isn't possible within i3 and I'm not looking to change that (neither here nor upstream) because it's a pretty complex mental model. If you want to do this you can write a script that determines the current workspace, takes a command as input and then uses the IPC (`i3-msg`) to forward the (modified) command.
