### ISSUE TITLE
FR: Per-window-class swallows child window

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#133]
Similar to this: http://dwm.suckless.org/patches/swallow

**Comment by clawoflight** [comment]
Wow. I never knew I needed this, but it would be awesome!

@sphaugh You should probably open this on [upstream i3](https://github.com/i3/i3) though.
Feel free to mention me if you want a +1 there :)

**Comment by Airblader** [comment]
Closing here because it's not related to i3-gaps as pointed out by @clawoflight.

That said, I don't think we'd want to add this upstream either. This feature simply encourages broken user workflows. Why not spawn a launcher like dmenu from the terminal such that the cwd is forwarded to the launcher?

But even that said, there's an open PR for window swapping and I'm fairly convinced you could implement this kind of swallowing using window swapping and the scratchpad.
