### ISSUE TITLE
Feature Request: fullscreen dimension & origin parameters

### ISSUE THREAD

**Issue by dixler** [Airblader/i3#146]
Currently, the fullscreen toggle works to completely engulf the screen and while this is nice sometimes, there are some times when I want more of a maximize function since I want to be able to see my panels with information like battery percentage, workspace information, and the time/date. I have a sort of hack that can do this by making a window float and resizing it, but it doesn't preserve the location of the window before it was resized, which makes it kinda annoying because my windows keep shuffling around.

Can there be an added functionality that allows fullscreen to have dimension and origin parameters so that fullscreen can be variably invoked?

**Comment by Airblader** [comment]
I've more than once wanted a function to fullscreen a window within its parent, which is roughly what you want. The problem here is that it goes directly against the specification and that's what I don't like. On the other hand, "resizing" it to be that size without actually marking it as fullscreen, in most cases, isn't what I want because it means the window will keep displaying all of its controls (think videos in a browser). 

Unfortunately I think this has to be tackled on specification level, which given Wayland development is unlikely to happen. And would have to be implemented all applications, which is even less likely. Sorry.
