### ISSUE TITLE
Cannot properly switch from tabbed layout to toggle split

### ISSUE THREAD

**Issue by Kyle-Thompson** [Airblader/i3#155]
**Version**:
Binary i3 version:  4.13-non-git © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13-non-git (pid 663)rl-c to abort…)
Loaded i3 config: /home/kyle/.config/i3/config (Last modified: Sat 01 Jul 2017 02:50:28 AM EDT, 198 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**What I did:**
With a screen layout of 3 terminals, one on the left half of the screen and the other two split vertically along the right half of the screen, I hit $mod+w (to switch to tabbed mode) then $mod+e (to switch back to toggle split) which worked but the title bar for the tabbed mode remained present after the switch. It was as if the tabs were now a part of my wallpaper.

**What I expected instead:**
After switching back to the regular view, the titles for the tabs should no longer be there.

**Comment by Airblader** [comment]
Are you running a compositor?

**Comment by Kyle-Thompson** [comment]
I might not have at the time but now I am (Compton specifically) and the problem is still there.

**Comment by Airblader** [comment]
The underlying issue here is that the gaps patch is a bit hacky. Usually compositing with »the correct« settings (which just differ for every setup). Unfortunately there's not really anything we can do about it other than a pretty major rewrite which is an open issue here: https://github.com/i3/i3/issues/1966

Closing this as a won'tfix / can'tfix, sorry.
