### ISSUE TITLE
No easy uninstall??

### ISSUE THREAD

**Issue by dinotheextinct** [Airblader/i3#170]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.14-69-g3b428476 (2017-09-14, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14-69-g3b428476 (2017-09-14, branch "gaps-next") (pid 6183)
Loaded i3 config: /home/dino/.config/i3/config (Last modified: Sat 23 Sep 2017 13:27:27 CEST, 2778 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

Why is there no easy way to uninstall the self build version of i3-gaps? I am encountering problems which I'd like to fix, but I can't seem to easily uninstall the installed version of i3-gaps.

**Comment by Airblader** [comment]
> Why is there no easy way to uninstall the self build version of i3-gaps?

Because ideally you're not building from source, see [this](https://github.com/Airblader/i3/wiki/Compiling-&-Installing#basics).

We've also discussed this in the past in upstream and for those reasons didn't include an uninstall target. Anyway, since we switched to autotools, `make uninstall` actually *should* work because it just comes out of the box. If it doesn't work, please report it upstream since i3-gaps doesn't modify the build environment.
