### ISSUE TITLE
Can't exit i3

### ISSUE THREAD

**Issue by Kyle-Thompson** [Airblader/i3#181]
Output of `i3 --moreversion 2>&- || i3 --version`:
`Binary i3 version:  4.13-non-git © 2009 Michael Stapelberg and contributors`
`Running i3 version: 4.13-non-git (pid 1010)l-c to abort…)`
`Loaded i3 config: /home/kyle/.config/i3/config (Last modified: Wed 15 Nov 2017 04:52:55 PM EST, 509623 seconds ago)`

`The i3 binary you just called: /usr/bin/i3`
`The i3 binary you are running: i3`

**What I did:**
I've slightly modified the text of the exit message. The command is now:
`bindsym $mod+Shift+e exec --no-startup-id "i3-nagbar -t warning -m 'Exit i3?' -b 'Yes' 'i3-msg exit'"`

I'm current running arch with no login manager/display manager. When I boot my computer I'm presented with a prompt and I run `startx i3` to load my i3 session. 

**What I saw:**

Clicking yes in the menu presented by pressing $mod+shift+e shuts down i3 but then leaves me with a black screen. The computer is still on but visually it is completely unresponsive.

**What I expected instead:**

To be returned to the prompt with which I launched i3.

**Comment by Airblader** [comment]
> shuts down i3

So everything you told i3 to do has worked. Sounds like you're having a problem with your login manager, not i3?

Can you switch to another TTY and see if i3 is still running? That way we can say for sure.

**Comment by Kyle-Thompson** [comment]
How should I go about switching to another TTY with a black screen? I must be missing something.

As a follow up though, just running `i3-msg exit` in a terminal produces the same results. blindly typing `startx i3` though does put me back into a fresh i3 session. I'm really unsure why I'm not able to exit back to my prompt though. This was working in the past.

Also:
> a problem with your login manager

I don't have a login manager. Aside from whatever the very barebones one Arch provides you with.

**Comment by Airblader** [comment]
> How should I go about switching to another TTY with a black screen?

Typically, Ctrl+Alt+F$n with something like $n=2. The default session usually runs either on TTY 1 or TTY 7.

> This was working in the past.

Assuming exiting i3 is something you do regularly, what changed since last time? Did you update your system? Change configurations?

> blindly typing startx i3 though does put me back into a fresh i3 session

That would imply that both i3 and the X server are in fact dead as you cannot start an X server within an already running X server. Which means I would pretty much expect this to be a kernel / graphics issue.

Another thing to try: instead of having startx launch i3, have it launch some other simple window manager such as twm. Then exit it and see if the issue occurs there as well.

**Comment by Kyle-Thompson** [comment]
I'll mess around with those suggestions and get back to you.

**Comment by Airblader** [comment]
I'm going to close this due to missing feedback and the higher likelihood of this not being an i3 issue.
