### ISSUE TITLE
[Feature Request] Respecting `desktop` attribute of windows

### ISSUE THREAD

**Issue by pasimko** [Airblader/i3#195]
It would be nice to be able to have windows on the desktop, so they are only displayed on empty workspaces.

https://github.com/wacossusca34/glava/issues/6

**Comment by Airblader** [comment]
See https://github.com/i3/i3/issues/2222 and https://github.com/i3/i3/issues/903. I'm not looking to adding this in i3-gaps without upstream support, so you could make your case in https://github.com/i3/i3/issues/903. However, since we don't really focus on eye candy in i3 there'd have to be a better usecase for desktop windows than an audio visualizer. The other ticket mentions a fork containing a patch to support these windows (somewhat) if you want to run it locally.

**Comment by jarcode-foss** [comment]
> I'm not looking to adding this in i3-gaps without upstream support

I do think this is probably more relevant for i3-gaps than upstream -- I agree with the sentiment that desktop windows don't make sense in i3 _if the user is expected to interact with them_, but "eye candy" windows have a larger use case in i3-gaps since the desktop isn't nessecarily obscured by visible windows.

Some users will want to display small terminals, system information (ie. conky), or visualizers on their desktop without it allocating any real screen real estate. Right now the only way to do this for i3 in application code is to draw on the root window.

If the answer to implementing this is still no, I will just end up writing the workaround described in the issue @pasimko referenced.

**Comment by Airblader** [comment]
> If the answer to implementing this is still no

Out of curiosity, if the answer was yes, would anyone be willing to implement this in a spec-compatible way in i3-gaps?
