### ISSUE TITLE
I3 freezing on startup of IntelliJ IDEA.

### ISSUE THREAD

**Issue by insertt** [Airblader/i3#205]
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.15.0.1 (03-13-2018) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15.0.1 (03-13-2018) (pid 13520)rt…)
Loaded i3 config: /home/insertt/.config/i3/config (Last modified: pią, 16 mar 2018, 07:19:50, 56191 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
URL to a logfile as per https://i3wm.org/docs/debugging.html:

`https://logs.i3wm.org/logs/5641206004449280.bz2`

**What I did:**
I launched IntelliJ IDEA, changed to other workspace and after a small amount of time changed to workspace with opened IntelliJ IDEA.

**What I saw:**

I saw running IntelliJ IDEA, but when i tried to do some i3 actions (change workspace, resize), it didn't work. I've switched to other tty and checked in htop what's going on, then I've sorted processes by cpu percent usage and i've seen 100% cpu usage on i3 process.

**What I expected instead:**
I expected to not freeze i3 after running IntelliJ IDEA.

**Comment by Airblader** [comment]
Was this a one time issue or does this happen every time? If the latter, does it also happen with normal i3?

**Comment by insertt** [comment]
It happens from time to time (especially after running desktop for quite a while) and yes, it also happen with normal i3.

**Comment by Airblader** [comment]
Thanks! I'll close this issue here then. Can you please post it on upstream i3? We should fix it there + it might get more attention there. Thanks!

When reporting it there: it would be good if you could attach gdb to the i3 process when it hangs and pull a backtrace. That would tell us where it is freezing. For that you just have to make sure you have the debug symbols installed. Then switch to another TTY (Ctrl+Alt+F2) and use `gdb $(which i3) $(pidof i3)` (might require sudo) to attach gdb (also see debugging docs).

You can do this with i3-gaps even if you report upstream. There's no difference between i3 and i3-gaps in these areas anyway.
