### ISSUE TITLE
[Feature Request] Render tabs instead of T[...] when inside a stacked container

### ISSUE THREAD

**Issue by HactarCE** [Airblader/i3#209]
When tabbed layouts are embedded in stacked layouts, it currently looks like this:
![image](https://user-images.githubusercontent.com/6060305/38590179-a02cea6a-3cfd-11e8-8721-2a39df5eace2.png)
This takes up three rows and it is impossible to see the titles of windows in the tabbed container without switching to it temporarily.

My suggestion is to render the row of tabs for both tabbed containers, instead of the `T[window1 window2]` row:
![image](https://user-images.githubusercontent.com/6060305/38590341-8a21fd0e-3cfe-11e8-965f-f2562101e7ed.png)
This is more informative, intuitive, and useful, while also taking up less screen space.

This could either become the new default behavior, or could be enabled with some setting.

This could also be extended to tabbed layouts embedded within other tabbed layouts, but in that case horizontal space is more constricted so it may make more sense to leave that the way it is.

**Comment by Airblader** [comment]
Thanks for the issue. I can definitely see the reasoning and do like the idea, but haven't thought about it yet and think there's a good chance this might not work for some reason or might turn out pretty complex. We'd have to think about it in detail.

In any case, we should handle this upstream in i3 itself, not i3-gaps (here I definitely do not wanna change it without upstream support :-) ), so can you please reopen the issue there? Thanks!

Final headsup: I wouldn't wanna do this via config. It's either all or none, otherwise it would become really, really complex.

**Comment by HactarCE** [comment]
Alright, that makes sense. I was thinking the same thing about this probably interfering with other things. I'll reopen this on the i3 repo. ([link](https://github.com/i3/i3/issues/3237))
