### ISSUE TITLE
Percentual gaps

### ISSUE THREAD

**Issue by lmichaelis** [Airblader/i3#240]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

Hey,
I'd really like to be able to define the size of the gaps using a percentage of the monitor's width (or, less peferably height). This should be calculated seperately for every monitor. I am asking because I can scale my polybar like that and it would be nice to scale my gaps accordingly so that they line up (see the image below).

Thank you!

![2018-09-28-094132_3200x1080_scrot](https://user-images.githubusercontent.com/20187490/46194839-da065880-c302-11e8-9bf9-804846bb97bd.png)

**Comment by Airblader** [comment]
I wouldn't mind adding this (keep the same syntax, just allow a value like `5%`), though it'd require a significant change in the gaps implementation (relatively speaking) since currently the gaps are calculated as the config is parsed. We'd now have to do that on-the-fly depending on the output the workspace is on. If someone can put together a prototype PR I'd be happy to look at it.

**Comment by keylime-unicorn** [comment]
@Airblader I would love to take a stab at this if you would be okay with it :)

**Comment by Airblader** [comment]
Thanks, I appreciate that. However, I have given this more thought. There's a couple of concerns I have

1. The complexity of evaluating this in different places is troubling, because my main focus is still the ability of maintaining i3-gaps to be up to date with upstream. The current gaps implementation is in very few, concentrated places, making this easy; this change, I believe, would make it spread to more places and thus increase friction when merging upstream.
2. I'm now questioning the usefulness of the percentage unit here; i3 does not support non-integer percentage values anyhwere, and having only integer value percentages is probably easily not a fine enough unit. While I believe that non-integer percentages can be useful, this would first have to be tackled in upstream i3.
3. On the other hand, this feature can be comfortably solved with a script that simply calculates the correct value in pixels. It would be a bit of an advanced script since it would both have to be able to take commands to change gaps and maybe even subscribe to events to know when workspaces are moved across outputs, but it's definitely doable.

For those reasons I'll actually close this for now. However, @camicarballo, you could definitely work on a script for this and link it in this issue as well.

We could later revisit implementing this in i3-gaps directly. At that point we'd have both a better feeling for how big the need for this is (which changes the benefit/cost calculation) and may also have support for non-integer values (which someone could raise as a feature request upstream).

Thanks for understanding!
