### ISSUE TITLE
Gap only mouse bindings 

### ISSUE THREAD

**Issue by faurehu** [Airblader/i3#248]
The gaps give us an opportunity to use this space for further i3 interaction. 

Personally, I'd love to be able to place my cursor on top of a gap and change workspaces on scroll. Any action on a gap should be interpreted as an interaction on i3.

Most mouses have 5 buttons (including scrolling up and down), so there is plenty of potential.

**Comment by Airblader** [comment]
Thanks for bringing this up!

Quite strongly related is issue #https://github.com/i3/i3/issues/2097. That solution should work for gaps as well. Note that this will create the binding everywhere, even over windows, but that is how i3 works by design as we do not have window-specific bindings (and the root window is just a window in that regard). If you want it to really be restricted to the root window, you'd have to find some shortcut tool that allows configuring that.

**Comment by faurehu** [comment]
@Airblader what do you mean by shortcut tool? Can you list some examples? Thanks.

**Comment by Airblader** [comment]
Something like shxkd or xbindkeys. I don't really know their capabilities so I don't know if one of them can do this particular thing, though. I haven't had to use them yet.
