### ISSUE TITLE
Compile errors when installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by arjvik** [Airblader/i3#269]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
I am attempting to install i3-gaps, and since (as far as I am aware of) Ubuntu does not provide i3 in its repos, I must compile it from source. I followed the instructions exactly as specified in [the wiki](https://github.com/Airblader/i3/wiki/Compiling-&-Installing) and I got this compile error:

```
In file included from ../../i3-gaps/src/ipc.c:12:0:
../../i3-gaps/src/ipc.c: In function ‘handle_get_version’:
../../i3-gaps/include/yajl_utils.h:19:50: error: expected expression before ‘)’ token
 #define y(x, ...) yajl_gen_##x(gen, ##__VA_ARGS__)
                                                  ^
../../i3-gaps/src/ipc.c:1033:5: note: in expansion of macro ‘y’
     y(integer, MAJOR_VERSION);
     ^
../../i3-gaps/include/yajl_utils.h:19:50: error: expected expression before ‘)’ token
 #define y(x, ...) yajl_gen_##x(gen, ##__VA_ARGS__)
                                                  ^
../../i3-gaps/src/ipc.c:1036:5: note: in expansion of macro ‘y’
     y(integer, MINOR_VERSION);
     ^
Makefile:2320: recipe for target 'src/i3-ipc.o' failed
make[1]: *** [src/i3-ipc.o] Error 1
make[1]: Leaving directory '/home/ubuntu/i3-gaps/build'
Makefile:1275: recipe for target 'all' failed
make: *** [all] Error 2
```

## Expected Behavior
Ideally, i3-gaps should compile without any errors.

## Reproduction Instructions
Follow the exact instructions outlined in the installation guide in the wiki.

## Version:
<pre>
i3 version: Latest commit on gaps-next branch (hash: `1fd20ce7e250ae2fb29d49efa1680ebb03331d8b`) 
</pre>

<pre>
- Linux Distribution & Version: Ubuntu 18.04.1 LTS
- Are you using a compositor (e.g., xcompmgr or compton): N/A
</pre>

**Comment by Airblader** [comment]
From that same wiki page:

Questions regarding the compilation will only be answered in the following cases:

You are working on providing a package for i3-gaps.
You need to compile from source to debug an issue in the latest version.
You have pinged your distribution's package maintainers to provide a proper package and can link to that request.
If one of these cases apply to you, please mention this in your issue. Other questions regarding how to compile (rather than a bug in the compilation) will be closed.

---

Try googling this error, you'll find more about it. It's not an iss with i3-gaps.
