### ISSUE TITLE
Allow control of smart_borders with IPC

### ISSUE THREAD

**Issue by RatanRSur** [Airblader/i3#293]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Desired Behavior
`i3-msg smart_borders xxx`

**Comment by Airblader** [comment]
I don't see the necessity of this. Just reload the config.

**Comment by RatanRSur** [comment]
Some time ago, you told me to do it via IPC:

https://github.com/Airblader/i3/issues/276

When I got around to it yesterday, I discovered that there's no way to hit this option with IPC

I understand this is an open source project and you likely have other things to do so if you wouldn't want to add it, would you be open to a PR?

**Comment by Airblader** [comment]
You cannot control smart_borders via IPC, but you do have the `border` command.

**Comment by Airblader** [comment]
Just to address this question too:

> I understand this is an open source project and you likely have other things to do so if you wouldn't want to add it, would you be open to a PR?

It's not just a question of someone having to do the work, but adding features comes at the cost of complexity and long term maintenance. This is the main reason to reject certain features :-)

**Comment by RatanRSur** [comment]
`border pixel n` will change the border if they exist but `smart_borders` will prevent that as long as they are on

**Comment by cpiber** [comment]
> I don't see the necessity of this. Just reload the config.

Then why have IPC at all? The point is that IPC can be used to dynamically control i3. "Reload the config" requires to first edit that config.

**Comment by Airblader** [comment]
If I were to rearchitect i3 from scratch — yeah, I'd do it so that the IPC is much more flexible with regards to the config. However, as it stands, config directives and commands are separate things and providing everything on both is significant maintenance effort, not to mention that many config directives exposed as runtime commands would require additional effort to implement.

Therefore the decision to expose something on the IPC is, unfortunately, a separate one from having a feature in the first place. We also recently merged support for including config partials, so "editing the config" before reloading is much easier to do programmatically. It's not perfect, but for this case I believe it's sufficient.

**Comment by cpiber** [comment]
I didn't know that was a thing, very useful.

I assume you are talking about https://github.com/i3/i3/pull/4420? So next version?

**Comment by Airblader** [comment]
Yes, that's it and it'll ship in 4.20.
