### ISSUE TITLE
Man pages & docs not building

### ISSUE THREAD

**Issue by vaskark** [Airblader/i3#298]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[ ] Documentation Request
[X] Other (Please describe in detail)
</pre>

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:  4.16.1-178-g31c0f1b8 (2019-05-14, branch "gaps-next")
</pre>

<pre>
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Ubuntu Disco
- Are you using a compositor (e.g., xcompmgr or compton): Compton
</pre>

Hi. For some reason I can't get the manual pages and docs to install when compiling from latest git source, even though it had worked in the past. Not sure what I'm doing wrong. Can someone offer some advice?
Thanks.

**Comment by Airblader** [comment]
Is there a [particular reason](https://github.com/Airblader/i3/wiki/Building-from-source) for why you are compiling from source?

**Comment by vaskark** [comment]
Well, I'm on Ubuntu Disco and there isn't an install package in the repos and I couldn't find one online.

**Comment by Airblader** [comment]
Thanks. I'm going to close this issue for a bunch of reasons in this case:

1. As explained in the wiki page, compilation questions are not supported unless one of the conditions listed there is met. When you have done so we can continue discussing it here, otherwise I recommend you ask the question over at /r/i3wm.
2. Your question is missing necessary information to investigate the issue: how do you build from source? What does "in the past" mean and can you bisect the issue to a specific commit or at least the version of i3-gaps?

I understand that the first point is a bit frustrating as it's not "your" fault, but a community as big as Ubuntu should be able to package i3-gaps for its users; the effort to support individual builds across various channels has simply become too tedious of a process. Therefore I insist that the community makes an effort to change this; if one of the conditions on the wiki page is met I'm happy to help here on GitHub as well.
