### ISSUE TITLE
[Question] - Contribute to i3 wiki

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#327]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

Debian Buster is not in Build from source wiki
I'd like to contribute to i3 wiki but there's no possibility as far as I can tell. I'd like to add instructions for Debian Buster - Building from Source, since one dependency has changed.

I think it I am not the only one who would contribute to the wiki. So I think it would be a great chance to improve it.

Also I saw that there's a Port for Freebsd where I couldn't find an instruction either. I'd be happy to add this, too.

If you don't want others to contribute to the wiki, please update Debian Buster like stretch, just that the package ```libxcb-shape0-dev``` is now ```libxcb-shape0```, since there exists no dev package. 

In Freebsd you have to 

```
pkg install i3-gaps
```

Thank you for your time, have a nice day!

 -  chrissly90

**Comment by Airblader** [comment]
Hi @chrissly90 ,

thanks so much for opening an issue. Indeed I don't want to open editing the wiki up because unfortunately there's no real review process in place. I intentionally keep the instructions for compilation from source somewhat vague and *really* want to discourage people from building from source.

That said, I updated the Debian instructions (I also removed "Stretch" from it – one Debian entry should be enough) and also added the FreeBSD entry (that one I am more than happy to add!). Thanks again for your help! Let me know if there's anything else that needs updated.
