### ISSUE TITLE
No systray icons after updating to the new AUR package

### ISSUE THREAD

**Issue by jonas-sk** [Airblader/i3#34]
After replacing i3-gaps with i3-gaps-git, i3bar is not showing systray icons anymore. Before I installed i3-gaps it also worked with the normal i3 4.8.3. 
[Here is the config](http://0bin.net/paste/bAfWwR5LInAUvsaS#9v-AwUJK90CpnHg0GTho8jmoZJPxlHuxP+VDqMr17UG)

Thanks for any help

**Comment by Airblader** [comment]
What do you mean "replacing i3-gaps with i3-gaps-git"? What is "i3-gaps" in this context (as opposed to i3-gaps-git)? The o4dev fork?
Also, your config restricts tray icons to DFP6. Is that screen active? Try removing that line and reloading to see if icons reappear.

If everything fails, it'd be nice to see whether installing vanilla i3 again fixes the issue; just make sure to comment out the fork-specific config. Then reinstall the fork without uncommenting the config changes so that you can test the fork exactly against the same config.

**Comment by jonas-sk** [comment]
> What do you mean "replacing i3-gaps with i3-gaps-git"? What is "i3-gaps" in this context (as opposed to i3-gaps-git)? The o4dev fork?

This is referring to the AUR packages - I was still running i3-gaps 4.7, when I saw you replaced the package

> Also, your config restricts tray icons to DFP6. Is that screen active? Try removing that line and reloading to see if icons reappear.

Yes, my primary monitor. I exchanged primary/DFP6/DFP7 to see if it was an issue with the parser/my monitor

> If everything fails, it'd be nice to see whether installing vanilla i3 again fixes the issue;

Will try that tomorrow. Thanks for the help

EDIT: Just tried some conky stuff and the tray icons are suddenly visible again. Now I just need to make a fancy .conkyrc. Seems to be an issue with i3status

EDIT2: And when reverting to i3status by reloading and restarting i3, the tray icons are now visible.

**Comment by Airblader** [comment]
I'm a little lost right now. When does it happen, when does it not? Do you still consider it an issue with i3 / i3bar? Also, if you edit your post I won't get a notification, so new comments would be better. :)

**Comment by Airblader** [comment]
So from reading this over and over again I gather that it's not an issue anymore. I will close the issue but if I was wrong to do so, feel free to let me know or reopen it.
