### ISSUE TITLE
system tray disappears on restart

### ISSUE THREAD

**Issue by benjaminBrownlee** [Airblader/i3#363]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

When `i3-msg restart` is executed, all currently visible icons in the system tray disappear along with the space allocated for the system tray (hence the icons are not simply transparent, the entire tray is gone).

## Expected Behavior

When `i3-msg restart` is executed, the environment is reloaded as usual with the system tray and icons returning to their proper position.

## Reproduction Instructions

Execute `i3-msg restart` directly or indirectly (ie adding a display). This only occured after my most recent system upgrade which included `i3-gaps`; I don't know all the potential applications responsible for the rendering of the system tray, but these upgrades included the following packages:

<details><summary>upgrades</summary><pre>
[2020-07-26T20:48:13-0700] [ALPM] upgraded iana-etc (20200707-1 -> 20200720-1)
[2020-07-26T20:48:13-0700] [ALPM] upgraded libutil-linux (2.35.2-1 -> 2.36-1)
[2020-07-26T20:48:13-0700] [ALPM] upgraded util-linux (2.35.2-1 -> 2.36-1)
[2020-07-26T20:48:14-0700] [ALPM] upgraded linux (5.7.9.arch1-1 -> 5.7.10.arch1-1)
[2020-07-26T20:48:14-0700] [ALPM] upgraded bbswitch (0.8-333 -> 0.8-334)
[2020-07-26T20:48:14-0700] [ALPM] upgraded llvm-libs (10.0.0-2 -> 10.0.1-1)
[2020-07-26T20:48:14-0700] [ALPM] upgraded compiler-rt (10.0.0-1 -> 10.0.1-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded clang (10.0.0-3 -> 10.0.1-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded dnsmasq (2.81-4 -> 2.82-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded harfbuzz (2.6.8-2 -> 2.7.0-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded mesa (20.1.3-1 -> 20.1.4-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded electron (9.1.0-3 -> 9.1.1-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded jasper (2.0.16-2 -> 2.0.17-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded libraw (0.19.5-3 -> 0.20.0-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded gegl (0.4.24-1 -> 0.4.24-2)
[2020-07-26T20:48:15-0700] [ALPM] upgraded harfbuzz-icu (2.6.8-2 -> 2.7.0-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded i3-gaps (4.18.1-2 -> 4.18.2-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded imagemagick (7.0.10.24-1 -> 7.0.10.24-2)
[2020-07-26T20:48:15-0700] [ALPM] upgraded libidn (1.35-3 -> 1.36-1)
[2020-07-26T20:48:15-0700] [ALPM] upgraded liblouis (3.14.0-1 -> 3.14.0-2)
[2020-07-26T20:48:15-0700] [ALPM] upgraded liburing (0.6-1 -> 0.7-1)
[2020-07-26T20:48:16-0700] [ALPM] upgraded linux-firmware (20200519.8ba6fa6-1 -> 20200721.2b823fc-1)
[2020-07-26T20:48:19-0700] [ALPM] upgraded linux-headers (5.7.9.arch1-1 -> 5.7.10.arch1-1)
[2020-07-26T20:48:19-0700] [ALPM] upgraded ndctl (68-2 -> 69-1)
[2020-07-26T20:48:19-0700] [ALPM] upgraded nodejs (14.5.0-1 -> 14.6.0-1)
[2020-07-26T20:48:19-0700] [ALPM] upgraded npm (6.14.6-1 -> 6.14.7-1)
[2020-07-26T20:48:19-0700] [ALPM] upgraded nvidia (450.57-3 -> 450.57-4)
[2020-07-26T20:48:19-0700] [ALPM] upgraded opencl-mesa (20.1.3-1 -> 20.1.4-1)
[2020-07-26T20:48:19-0700] [ALPM] upgraded pipewire (0.3.6-1 -> 0.3.7-1)
[2020-07-26T20:48:19-0700] [ALPM] upgraded rubygems (3.1.3-1 -> 3.1.4-1)
[2020-07-26T20:48:20-0700] [ALPM] upgraded pycharm-community-edition (2020.1.3-1 -> 2020.1.4-1)
[2020-07-26T20:48:20-0700] [ALPM] upgraded python-lazy-object-proxy (1.5.0-2 -> 1.5.1-1)
[2020-07-26T20:48:20-0700] [ALPM] upgraded python-numpy (1.19.0-1 -> 1.19.1-1)
[2020-07-26T20:48:20-0700] [ALPM] upgraded python-matplotlib (3.3.0-1 -> 3.3.0-3)
[2020-07-26T20:48:20-0700] [ALPM] upgraded python-pygments (2.6.1-2 -> 2.6.1-3)
[2020-07-26T20:48:20-0700] [ALPM] upgraded python-scipy (1.5.1-1 -> 1.5.2-1)
[2020-07-26T20:48:21-0700] [ALPM] upgraded python-urllib3 (1.25.9-1 -> 1.25.10-1)
[2020-07-26T20:48:21-0700] [ALPM] upgraded python-yaml (5.3.1-1 -> 5.3.1-2)
[2020-07-26T20:48:21-0700] [ALPM] upgraded qemu (5.0.0-7 -> 5.0.0-8)
[2020-07-26T20:48:21-0700] [ALPM] upgraded scrot (1.3-1 -> 1.4-1)
[2020-07-26T20:48:21-0700] [ALPM] upgraded sudo (1.9.1-1 -> 1.9.2-1)
[2020-07-26T20:48:22-0700] [ALPM] upgraded zenity (3.32.0+17+gfb0938f-2 -> 3.32.0+17+gfb0938f-3)
[2020-07-26T20:49:28-0700] [ALPM] upgraded betterlockscreen (3.0.1-4 -> 3.0.1-5)
</pre></details>

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.2 (2020-07-26) (pid 6724)abort…)
Loaded i3 config: /home/benjamin/.config/i3/config (Last modified: Mon 27 Jul 2020 04:40:06 PM MST, 364 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

*Reproducible under the default configuration (pasted below anyways).*
<details><summary>Config file</summary><pre>
# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!
#
# This config file uses keycodes (bindsym) and was written for the QWERTY
# layout.
#
# To get a config file with the same key positions, but for your current
# layout, use the i3-config-wizard
#

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

# Use pactl to adjust volume in PulseAudio.
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# use these keys for focus, movement, and resize directions when reaching for
# the arrows is not convenient
set $up l
set $down k
set $left j
set $right semicolon

# use Mouse+Mod1 to drag floating windows to their wanted position
floating_modifier Mod1

# start a terminal
bindsym Mod1+Return exec i3-sensible-terminal

# kill focused window
bindsym Mod1+Shift+q kill

# start dmenu (a program launcher)
bindsym Mod1+d exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym Mod1+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym Mod1+$left focus left
bindsym Mod1+$down focus down
bindsym Mod1+$up focus up
bindsym Mod1+$right focus right

# alternatively, you can use the cursor keys:
bindsym Mod1+Left focus left
bindsym Mod1+Down focus down
bindsym Mod1+Up focus up
bindsym Mod1+Right focus right

# move focused window
bindsym Mod1+Shift+$left move left
bindsym Mod1+Shift+$down move down
bindsym Mod1+Shift+$up move up
bindsym Mod1+Shift+$right move right

# alternatively, you can use the cursor keys:
bindsym Mod1+Shift+Left move left
bindsym Mod1+Shift+Down move down
bindsym Mod1+Shift+Up move up
bindsym Mod1+Shift+Right move right

# split in horizontal orientation
bindsym Mod1+h split h

# split in vertical orientation
bindsym Mod1+v split v

# enter fullscreen mode for the focused container
bindsym Mod1+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym Mod1+s layout stacking
bindsym Mod1+w layout tabbed
bindsym Mod1+e layout toggle split

# toggle tiling / floating
bindsym Mod1+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym Mod1+space focus mode_toggle

# focus the parent container
bindsym Mod1+a focus parent

# focus the child container
#bindsym Mod1+d focus child

# move the currently focused window to the scratchpad
bindsym Mod1+Shift+minus move scratchpad

# Show the next scratchpad window or hide the focused scratchpad window.
# If there are multiple scratchpad windows, this command cycles through them.
bindsym Mod1+minus scratchpad show

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym Mod1+1 workspace number $ws1
bindsym Mod1+2 workspace number $ws2
bindsym Mod1+3 workspace number $ws3
bindsym Mod1+4 workspace number $ws4
bindsym Mod1+5 workspace number $ws5
bindsym Mod1+6 workspace number $ws6
bindsym Mod1+7 workspace number $ws7
bindsym Mod1+8 workspace number $ws8
bindsym Mod1+9 workspace number $ws9
bindsym Mod1+0 workspace number $ws10

# move focused container to workspace
bindsym Mod1+Shift+1 move container to workspace number $ws1
bindsym Mod1+Shift+2 move container to workspace number $ws2
bindsym Mod1+Shift+3 move container to workspace number $ws3
bindsym Mod1+Shift+4 move container to workspace number $ws4
bindsym Mod1+Shift+5 move container to workspace number $ws5
bindsym Mod1+Shift+6 move container to workspace number $ws6
bindsym Mod1+Shift+7 move container to workspace number $ws7
bindsym Mod1+Shift+8 move container to workspace number $ws8
bindsym Mod1+Shift+9 move container to workspace number $ws9
bindsym Mod1+Shift+0 move container to workspace number $ws10

# reload the configuration file
bindsym Mod1+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym Mod1+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym Mod1+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym $left       resize shrink width 10 px or 10 ppt
        bindsym $down       resize grow height 10 px or 10 ppt
        bindsym $up         resize shrink height 10 px or 10 ppt
        bindsym $right      resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left        resize shrink width 10 px or 10 ppt
        bindsym Down        resize grow height 10 px or 10 ppt
        bindsym Up          resize shrink height 10 px or 10 ppt
        bindsym Right       resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or Mod1+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym Mod1+r mode "default"
}

bindsym Mod1+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
}

#######################################################################
# automatically start i3-config-wizard to offer the user to create a
# keysym-based config which used their favorite modifier (alt or windows)
#
# i3-config-wizard will not launch if there already is a config file
# in ~/.config/i3/config (or $XDG_CONFIG_HOME/i3/config if set) or
# ~/.i3/config.
#
# Please remove the following exec line:
#######################################################################
exec i3-config-wizard

</pre>
</details>

**Still working on producing/cleaning up a useful logfile.**

Open to advice and suggestions for things to look for considering the current issue.

<pre>
Logfile URL:
</pre>

<pre>
- os: Arch Linux x86_64
- kernel: 5.7.10-arch1-1
- issues are reproducible with or without compositor (picom)
- issues are reproducible with or without fancy bars (i3status-rs, polybar)
</pre>

**Comment by benjaminBrownlee** [comment]
Sorry, it appears this is already an active issue on the base i3 repository. You can find it here: https://github.com/i3/i3/issues/4159.

**Comment by Airblader** [comment]
Yes, let's please track it there. Thanks!

**Comment by ArchI3Chris** [comment]
Same problem. Due to other problems I ran a full upgrade. As usually, some things stopped working. So, no way around rebooting. After that, my whole bar (not the panel, the stats bar => i3bar) threw an error. Has cost me a lot of time to figure out how to get it back. The bar is back. Turns out, the tray icons are not. They get loaded, then they disappear. Why don't people test the stuff they develop before they release it?!?!?!?!

Seems, the problem is coming from upstream:
https://github.com/i3/i3/issues/4159

But it takes two to play this game. Seems, Arch management has implemented an unstable version of i3-wm in the default repo instead of the testing repo! How did that happen? Great. I have 3 tray icons. But I use them... I don't know... like hundred times per day, every day? Not exactly a small hickup. Small mistake. Has cost me HOURS to figure it out. And at the end, no solution! For just a little upgrade. Sad. Really sad!

**Comment by Airblader** [comment]
We welcome more users to try out the unstable branch before release. The more volunteer, the fewer bugs will make it to a stable release. We also welcome any contributions to the test suite, of course. Bugs happen in each and every piece of software. Arch in particular moves fast; if you want software tht went through a much longer phase of stability testing I recommend you switch to something like Debian.

In the meantime instead of getting upset you can also just downgrade i3 temporarily. Anger doesn't help you, us or anyone else.

**Comment by ArchI3Chris** [comment]
Let me advice you to think about what you are saying before you throw random comments without thinking. The idea of Arch Linux is not testing. The idea is a user-managed distro that's primarily for desktop use. Using the latest stables and using unstable testing stuff are two different things. Arch does have a testing branch and a mainstream one. Take a look in the pacman config file if you don't believe me. The evidence is there. The testing repo is COMMENTED by default! So it is in my config file! If I want to edit source code, I use Gentoo, not Arch. Don't talk about things you don't understand. This crap does not belong in the stable branch! It belongs in the testing branch. And just firing it up once immediately shows, that tray icons are missing. How blind does one have to be, to miss that? Just because bugs are everywhere doesn't mean, there is sense in making it the standard and accepting flaws everywhere. This is EXACTLY WHY flaws and problems are everywhere. Because one uses the other as excuse. This is really ridiculous. Find a role model UPSTREAM not downstream! Mistakes happen. But don't defend it if you don't want flaws! You are offering an excuse and justifying poor quality. Are you just developing to have something to develop, or are you developing the stuff to get the work done? Do you want people to use it or do you just need something to do? If you just need something to do, play Pokemon but don't develop software for users! Do you understand, that AVERAGE USERS are dealing with problems all day, because developers think, they release it first and correct errors later? User are not software testers! I am not a developer. I am a USER! If I want to develop and test software, I use Fedora, not Arch! You don't encourage me to help, by stealing my valuable time. You are just making me angry. This is not on me. This is on YOU! I'm not angry, because I'm using the wrong distro. I'm angry because you think, it's ok for stuff to not work and for users to be your testing engineer. WAKE UP! I'm not using Debian on purpose. I'm using Arch for a reason. That doesn't give Arch or developers the right to use me as a software tester against my will! If you want to develop software, do it right. Don't expect other people to correct your crappy work! Do you know, why I'm not developing software? I don't do it, because I'm not a developer and I can't offer quality work to other people. The difference between you and me is, I know it and you don't! You defend the crap that people are putting out there. And that's the crap users are dealing with all day. If you wanna be a developer, be a developer. If you are not capable of being one, find another job. I'm not a developer. I'm a user. I need it to work, to get my work done. MY WORK! NOT YOURS! Got it? If you wanna be a developer, stop the exuses and be a developer! That means, release it when it's done and ready, not when it's half-baked! There is a difference between not being perfect and not even getting the basics right. Know why I ran the upgrade? Because something didn't work. An application crashed unusually often. Know when? Moving from one track to the next. That's BASICS for this software. THIS CAN'T HAPPEN! If you think, that is what software development is about and if you need to defend that, find another job and leave development to those who know what they are doing and don't tell me what to use. I'm a USER. I know exactly what to use. FYI: this thing has been working for me for years. So, WHY DID YOU DESTROY IT IN FIRST PLACE! SOMETHING THAT HAS BEEN WORKING FOR YEARS BEFORE? I've been using it for years, because it was the solution that did work for me. NOW IT DOESN'T! Funny thing... testing it and releasing it when it's ready, this can't happen. Testing it in the testing branch and keeping it out of the mainstream stable, this can't happen. And it shouldn't happen either! Again... how hard is it to miss, that tray icons are missing? THINK... before you write. This is not some random rant. This is simple logic. Make it work, or keep it to yourself. Users are not your testers. This is one of the reasons why people don't use Linux. Not because people rant about problems and are impolite. But because the crap doesn't work, because developers think, users are their software testers and have to correct the error developers produce all day!


> We welcome more users to try out the unstable branch before release. The more volunteer, the fewer bugs will make it to a stable release. We also welcome any contributions to the test suite, of course. Bugs happen in each and every piece of software. Arch in particular moves fast; if you want software tht went through a much longer phase of stability testing I recommend you switch to something like Debian.
> 
> In the meantime instead of getting upset you can also just downgrade i3 temporarily. Anger doesn't help you, us or anyone else.

**Comment by EgonSpengler** [comment]
That's a very long-winded way to agree that you should be using another distro that is for "average users." If you want people being paid to do QA, get it from a distribution that pays people to do that, not from one that's notorious for needing skilled troubleshooting, when (per the linked issue) a simple downgrade would solve your problem in minutes.

**Comment by Airblader** [comment]
Be that as it may, I frankly don't care, your criticism regarding Arch is in the wrong spot here. I don't publish the Arch package, I only maintain the unstable AUR package, and even for that this is the wrong place. Stop using i3-gaps for all I care, your tone is entirely inappropriate.

I'm cutting this pointless discussion off at this point.
