### ISSUE TITLE
Solid coloured row of pixels on the top of the screen of one monitor (only on i3)

### ISSUE THREAD

**Issue by coletonodonnell** [Airblader/i3#364]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
There is a solid coloured row of pixels on the top of my monitor, and I think I know why, I just don't know how to fix it. 

## Expected Behavior
There should just be the wallpaper right there

## Reproduction Instructions
You will need a setup as follows, two vertical monitors sandwiching a horizontal monitor, each 1920x1080. I thought this was originally an issue with polybar, but I decided to remove the bar and see if the issue was still there, and it was, from there I decided to try GNOME and I was pleasantly surprised to see the glitch gone. This leads me to believe it is either an issue with i3 or the compositor. Here is a [screenshot](https://imgur.com/a/K6J01nv) of what the entire thing is, right now the colour of the glitched row of pixels is the same as there in the screenshot, a solid orange across.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
`Binary i3 version:  4.16.1-186-gf3fffbae (2020-03-01, branch "makepkg") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1-186-gf3fffbae (2020-03-01, branch "makepkg") (pid 1870)
Loaded i3 config: /home/admin/.config/i3/config (Last modified: Sun 09 Aug 2020 07:59:55 PM EDT, 1583 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3`
</pre>

## Config file
The config was quite large and I couldn't get it formatted properly so here is a [link to it](https://pastebin.com/0HMxFbpt) 

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version:
OS: Arch Linux 
Kernel: 5.7.12-arch1-1
- Are you using a compositor (e.g., xcompmgr or compton):
I don't think so, I have picom installed but I don't recall setting it up, and "inxi -Gxx | grep compositor" yields no results.</pre>

**Comment by coletonodonnell** [comment]
A note, I did mention " i3 or the compositor." I wrote that when I thought I had a compositor, but on further thought I don't think I do, which I mentioned at the 'Are you using a compositor" bit.

**Comment by Airblader** [comment]
Thanks for reporting this and excuse the late response. My initial thought is that this isn't an i3 issue because we do not control the root window whatsoever, and if there is no window in that space, there is nothing that i3 would render into at all. You can *try* running a compositor to see if it improves the situation. My guess would go towards graphics driver and/or (combination with) missing root window management, so explicitly setting the root window (with another tool than what you do now) could also be worth a shot.

In any case I'm 99.9% this is not i3-gaps specific so I'd ask you to verify under vanilla i3 and if necessary open the issue there. Thanks!
