### ISSUE TITLE
Build error: bunch of multiple definitions from ld

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [Airblader/i3#365]
When I try to build I3-gaps I get probably a couple of hundred errors like:
```
/usr/bin/ld: src/i3-xinerama.o:/home/rein/i3/build/../../i3/include/atoms_rest.xmacro:15: multiple definition of `A_I3_PID'; src/i3-assignments.o:/home/rein/i3/build/../../i3/include/atoms_rest.xmacro:15: first defined here
```

I am on ArchLinux
I followed built instructions, with the exception of disabling the man pages (gave me some errors)

**Comment by Airblader** [comment]
1. Please read https://github.com/Airblader/i3/wiki/Building-from-source
2. Please recreate the issue, if necessary, with proper information and using the issue template.
3. Since i3-gaps does not modify the build from i3 it'd likely be an upstream issue (if there is an issue) so please also try vanilla i3 and open it there instead if it can be reproduced.

Thanks!

**Comment by LevitatingBusinessMan** [comment]
Thanks for the quick response Airblader,
I did thoroughly read the wiki (which I mentioned)

I'll make a better issue tonight if I find the time
