### ISSUE TITLE
[wiki] wrong command  in "Building from source" 

### ISSUE THREAD

**Issue by jlysiak** [Airblader/i3#382]
Hi! On wiki page in section [Building](https://github.com/Airblader/i3/wiki/Building-from-source#building) the last command is  `meson install` and probably there should be `ninja install`.
At least, the latter worked for me.

**Comment by Airblader** [comment]
Thanks for raising this. I've decided to follow the PACKAGE_MAINTAINER documentation here and rather recommend going to the meson website, and removed the installation step (that's not part of compiling anymore). Please note that compiling and installing on your own is highly discouraged. Thanks!

**Comment by enricozb** [comment]
Sorry to comment on a closed issue but, is there any chance we could add back into the wiki that `ninja install` is necessary to install i3? Or at least remove references to the word "install" since the current documentation only builds?

**Comment by Airblader** [comment]
I've removed the erroneous "install" word from the instructions. Again, this is something only people who have a basic understanding of what they're doing should do in the first place.

**Comment by enricozb** [comment]
Fair enough, I have no option but to do this every time I update i3-gaps though, because I have a personal patch for removing a 1 pixel border between the bar and windows, referenced in this reddit post [here](https://www.reddit.com/r/i3wm/comments/64ud5z/1px_gap_between_bar_and_window_border/dg5hjsz?utm_source=share&utm_medium=web2x&context=3). So I usually reference this documentation.

Thanks for the quick fix.
