### ISSUE TITLE
Persistent container Proposal

### ISSUE THREAD

**Issue by s-ol** [Airblader/i3#40]
This is comparably a huge feature to implement, but something I would find really useful:

fixed size containers that stay open even without children and that allow clients to be `assigned` to (in a similar fashion to workspaces).

This would allow side-by-side development with graphical applications that need to be restarted when iterating a lot.

**Comment by Airblader** [comment]
You mean something similar to the placeholder feature of i3 in 4.9? 

Something like this might even be a better idea for a standalone program rather than a feature of the window manager.

**Comment by s-ol** [comment]
Didn't know about placeholders, looking it up now

**Comment by Airblader** [comment]
They won't do exactly what you want. But they might make implementing this easier. I haven't read the source code for them at all yet, so this requires some digging to see how complex it would be.

**Comment by s-ol** [comment]
yeah, that looks close. Except I can't find how to generate one without a layout file and I guess they won't stay when the client terminates after being swallowed.

**Comment by Airblader** [comment]
Yeah, exactly. But like I said, maybe the necessary infrastructure is there and could be reused for this. Like, say, a flag that tells the placeholder to come back when the client terminates.

Then, obviously, you need a way to add this during runtime rather than a layout file. I will have to check if the code can be reused. It will probably be the biggest factor in whether or not I can do this. 

I like the idea though. I've certainly had similar situations.

**Comment by Airblader** [comment]
As you can read in the referenced issue, Michael doesn't generally oppose to this change. So if it turns out to be a bigger change, it might still be possible if it gets merged upstream since it would nullify the maintenance effort.

I don't know when I will have time to get into this, though. I have to fully understand the placeholder feature first, which I don't as of now.

**Comment by Airblader** [comment]
There's actually no need for this duplicated issue now. I'll close this issue as it is tracked in i3/i3 itself.
