### ISSUE TITLE
Config include feature from i3

### ISSUE THREAD

**Issue by dabljues** [Airblader/i3#408]
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

I've skipped the template since this is just a question about a pending feature. Basically as discussed [here](https://github.com/i3/i3/issues/4192) there is now a possibility to include an i3 config file into another one. There's even a branch like this on i3-gaps repo: https://github.com/Airblader/i3/tree/include.

My question is: is this branch going to be merged or do people who want to use the "include" feature in i3-gaps have to install from this branch? (which would be an inconvenience, since I am sure most of people do it via package managers).

**Comment by Airblader** [comment]
i3-gaps is always kept up to date with upstream i3, so any feature which lands in i3 also lands in i3-gaps. This particular feature has been merged already, but there was no release yet, so to use it currently you'd have to build i3 / i3-gaps yourself. Otherwise you'll just have to wait for 4.20 to be released.

**Comment by dabljues** [comment]
Oh, how did I miss that. Thank you!
