### ISSUE TITLE
No borders on nautilus

### ISSUE THREAD

**Issue by rainerborene** [Airblader/i3#42]
![screenshot-2015-03-09](https://cloud.githubusercontent.com/assets/101501/6565828/c174e082-c691-11e4-92a6-363b4a4ed680.png)

any idea why this is happening? 

here's my dotfiles: https://github.com/rainerborene/dotfiles

**Comment by Airblader** [comment]
Do they come back when you float the window? I think it removes its decorations because it thinks that it's maximized. It's just a guess though. It can probably be fixed in the gtk theme.  

Since this is not an issue of my fork, can you please ask this question over at faq.i3wm.org? I'll close the issue here for that reason. Maybe disable gaps when showing it there though :) 

Relevant question might be 
https://faq.i3wm.org/question/346/how-can-i-use-i3-in-gnome-2-de/

**Comment by rainerborene** [comment]
No, they don't come back on floating mode. If I close `compton` borders works.

**Comment by Airblader** [comment]
I'm still convinced it's not an issue of my fork. Also, I use thunar and can see borders just fine. Can you post your `.compton.conf`? I'd still advise taking this to maybe the compton repository, then.

**Comment by rainerborene** [comment]
https://github.com/PCMan/gtk3-nocsd solved the problem.

**Comment by Airblader** [comment]
Glad it worked out!

**Comment by Blueblur** [comment]
Some gtk 3 applications replace window manager borders with their own IIRC. It seems that Nautilus is one of these.

**Comment by beanaroo** [comment]
I had this issue when making use of `for_window [class="^.*"] border pixel 0` or `new_window/float none`
Using only:

```
for_window [class="^.*"] border pixel 4
```

gaps and borders work on all windows, including csd, contrary to the [README's requirements.](https://github.com/Airblader/i3#gaps)

**Comment by Airblader** [comment]
@beanaroo I agree that the README is a bit misleading. Actually, as you found, you can set any border width. What you can't do with gaps is the "normal" borders (i.e., with title decoration), because then i3 starts creating pixmaps.

**Comment by Airblader** [comment]
I've updated the README a bit.
