### ISSUE TITLE
Smart gaps?

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#46]
Presently, inner gaps are still applied if there is only one container on the screen even if smart_borders is enabled. This seems counter to the definition of inner gaps as a sort of transparent window border (gaps between containers) while outer gaps are a padding around the edge of the screen. 

smart_borders on should hide inner gaps (i3 looks ugly with modest gaps if only one window is open).

**Comment by Airblader** [comment]
`smart_borders` is about displaying borders on a container if it's the only one on a workspace. There is a `smart_borders no_gaps` to only apply smart borders if no gaps are used. But smart borders should not _set_ gaps, that would be backwards.

As stated in the README, gaps on workspace borders use the _sum_ of inner and outer gaps and there are reasons why they do.

Do you have outer gaps set at all? I could consider adding a `smart_gaps on` analogy, but that would disable all gaps if it's the only container (inner and outer).

**Comment by ghost** [comment]
> Do you have outer gaps set at all?

No

A smart_gaps analogy would be wonderful, though

**Comment by Airblader** [comment]
I'll try to implement this. I don't expect this to be complicated, but I probably won't get around to doing it until the weekend. In any case I'll rely on you testing the patch before I merge it.

**Comment by Airblader** [comment]
@vaimwaip Please check out `feature-smart-gaps` and add `smart_gaps on` to your config and see whether it behaves the way you expect it to.

Note that it branches off of `gaps`, so if you currently use `gaps-next`, please let me know and I will rebase it.

**Comment by ghost** [comment]
It works, except in two cases. When you open two windows (workspace_layout default), switch to tabbed, and then switch to split again, and when a multiwindow container goes back to being the only container on the workspace (open three, move one to a new container, close it). The gaps do not return until a new container is created. This behaviour was not present prior to this feature.

**Comment by Airblader** [comment]
Thanks for the feedback. I will look into these, but they might prove a little tricky.

> When you open two windows (workspace_layout default), switch to tabbed, and then switch to split again

This one I understand and can reproduce.

> and when a multiwindow container goes back to being the only container on the workspace (open three, move one to a new container, close it)

I don't understand the last part. I can reproduce the unexpected behavior if I open two windows, stack/tab them and then close one of them. Is that what you meant or does the part in parentheses describe a third case?

**Comment by ghost** [comment]
It describes the second case.

**Comment by Airblader** [comment]
So I think I have the problem: what I do is I check in the tree whether the workspace has <= 1 children. In case 1, when I open two windows and tab them, I have the following layout:

```
   [workspace]
        |
    [tabbed]
        |
       / \
[urxvt]   [urxvt]
```

When changing back to a split layout, we _expect_ the following layout which would work as expected because the workspace now has two children:

```
   [workspace]
        |
       / \
[urxvt]   [urxvt]
```

However, what we are _really_ left with is this:

```
   [workspace]
        |
    [splith]
        |
       / \
[urxvt]   [urxvt]
```

And now the workspace still only has one child, hence the check doesn't work.

The obvious answer is to flatten the tree. I'll have to think about it, though, and see how it works out.

**Comment by Airblader** [comment]
@vaimwaip Can you please check the branch out again and experiment more with it?
_Edit:_ Please hold on with compiling, there's an error
_Edit2:_ OK, you can test it now. Please also try to muck around with nested floating containers. I don't really want to support them, but at least make sure that it doesn't crash or anything.

I went with counting children correctly rather than flattening the tree since the latter might cause behavior I can't foresee.

**Comment by ghost** [comment]
Sorry for the delay, I was without internet. No bugs here.

**Comment by Airblader** [comment]
@vaimwaip Thanks for testing. I have merged it into `gaps` and `gaps-next`.

**Comment by ghost** [comment]
I missed something. Woops. Simple fix.

```
diff --git a/src/con.c b/src/con.c
index 231a17c..7c79746 100644
--- a/src/con.c
+++ b/src/con.c
@@ -1170,7 +1170,8 @@ Con *con_descend_direction(Con *con, direction_t direction) {
  */
 Rect con_border_style_rect(Con *con) {
     if ((config.smart_borders == ON && con_num_visible_children(con_get_workspace(con)) <= 1) || (config.smart_borders == NO_GAPS && calculate_effective_gaps(con).outer == 0)) {
-        return (Rect){0, 0, 0, 0};
+        if (!con_is_floating(con))
+            return (Rect){0, 0, 0, 0};
     }

     adjacent_t borders_to_hide = ADJ_NONE;
```

**Comment by Airblader** [comment]
@vaimwaip Thanks, I've pushed the fix. :)
