### ISSUE TITLE
Set gaps on a per-output basis

### ISSUE THREAD

**Issue by s-ol** [Airblader/i3#52]
I recently acquired a second, larger monitor and it would be nice to set the inner/outer gaps seperately for each output, not for a workspace (so I can have larger gaps and some outer gaps on the larger monitor).

I don't really know whether and how that would fit into the current protocol, if you don't think it's fitting then I will have to consistently assign my workspaces to my outputs.

**Comment by Airblader** [comment]
Yeah, I'd actually like to avoid this. For one, the usecase seems limited to me. Secondly, it bring up the problem of rivaling settings (which has priority – output-level or workspace-level?). But lastly, and most importantly, I would suggest that you simply use a tool such as i3subscribe or any of the available IPC tools for i3, subscribe to the workspace event and handle this yourself. Shouldn't be too hard, just look for `change: "init"`.

If gladly help if you have trouble writing such a script. I hope this is okay for you!

**Comment by Big-Tree** [comment]
Hi @Airblader, I thought I'd say that this feature would be useful to me.  I just got a 4k monitor and I still have a smaller 1080p secondary monitor.  Setting the gaps for a specific workspace has been my work around although this has been made more complicated because I use [i3-workspace-groups](https://github.com/infokiller/i3-workspace-groups) which messes with the names.
