### ISSUE TITLE
Merging with i3

### ISSUE THREAD

**Issue by ghost** [Airblader/i3#64]
How about to merge all features (gaps, smart borders, i3bar height) to official i3?

**Comment by Airblader** [comment]
Won't happen for a multitude of reasons.

**Comment by ghost** [comment]
So. Can I help in i3-gaps development?

**Comment by Airblader** [comment]
I'm generally happy about pull requests, but I don't really have any plans for features in i3-gaps. Most features I develop end up in i3 itself and find their way into i3-gaps through merging back.

If there's specific features you want, open tickets for them so they can be discussed.

**Comment by MaxMatti** [comment]
@Airblader Could you elaborate on why merging won't happen or link to a more detailed explanation?

**Comment by Airblader** [comment]
There are two reasons and they're fairly simple:

1. Gaps go against what i3 is intended to achieve in upstream. 
2. Gaps are implemented as more of an hack rather than a clean patch. They also conflict with the title bar feature. 

So even if we wanted this feature in upstream, which we don't, it wouldn't hold up to the quality standards we expect.
