### ISSUE TITLE
Dynamic margin and centering of terminal emulators in containers

### ISSUE THREAD

**Issue by 602k4** [Airblader/i3#81]
There is a known issue with the sizing of terminar emulator because it only fits to column size multiplier. I have read many perfeccionist sick people like me that uses too much ncurses terminal applications and can't stop watching the f***ing unperfect margin in the right side of window containers.

In a lucid dream I come to the perfect solution being implemented in i3-gaps as the first tilling wm solving this ancient issue. Maybe the great Airblader or some other experienced hacker could make a "dynamic" margin (gap) inside terminal containers (manually specifing the name on config file the name of window, or common used hardcoded, I don't know what is better).

That margin will grow a few pixels, just to adapt inner width to a columns compatible size and center the terminal emulator window in the container. Boom, solved with ease and now the perfeccionist feeling makes me fly.

I don't have the required experience to make this patch but I could try to make it if some gives me a short procedural method and which files contain the required parts of code.

Thanks by reading and your daily effort.

**Comment by Airblader** [comment]
> I have read many perfeccionist sick people like me that uses too much ncurses terminal applications and can't stop watching the f***ing unperfect margin in the right side of window containers.

I don't see how this gets any better if instead the containers themselves are sized inconsistently.

> manually specifing the name on config file the name of window, or common used hardcoded, I don't know what is better

Hardcoded is a terrible idea. And using match criteria yields the problem that there is no information at which point some ncurses application is running within a terminal window.

> There is a known issue with the sizing of terminar emulator because it only fits to column size multiplier.

Exactly, it's an issue of the emulator. Go file the problem there. The window manager decides how big a window is, period.

> I could try to make it if some gives me a short procedural method and which files contain the required parts of code.

i3 used to support this hint for tiled windows. You can learn why it was removed (and how it used to work) by looking at
- https://github.com/i3/i3/issues/540
- 40b12c0a4d15ca44bdcf23b4c0e297f67ddf4b1b

This isn't something I'm looking to change because I think the decision is reasonable, sorry.
