### ISSUE TITLE
Feature Request: Make `hide_edge_borders` work even with gaps

### ISSUE THREAD

**Issue by rastertail** [Airblader/i3#92]
Currently when there are gaps, `hide_edge_borders` still shows borders that would be hidden if there were no gaps. I made a lazy change to `con_adjacent_borders` to do this which you can see in [this](https://github.com/rytone/i3/commit/5d5ca8f1a0d7a9b7486b6b765a18f3cb8078cd22) commit. A config option for this would be nice, however this is my first time even looking at the i3 codebase, so I have no idea how I should implement it.

**Comment by Airblader** [comment]
Can you elaborate on why this should work? Hiding edge borders is about hiding the border _at_ the edge with the rationale that the border is unnecessary because there is nothing it separates from the window (the physical screen is a pretty obvious boundary already). With gaps, this is no longer true, so I don't see the rationale for hiding individual edges in this case (and frankly can't imagine how that'd not look weird).

Or are you maybe just looking for `smart_borders no_gaps`?

**Comment by rastertail** [comment]
The use of this is really specific, and now that I think about it, it should really just exist as a separate fork. I saw [this](http://i.imgur.com/bqTIRRs.png) and thought that it looked pretty cool with the padding in the terminal, how the borders of the tmux panes didn't reach the edge of the screen. So the idea is that you have a 1 or 2 pixel border and only outer gaps, and your wallpaper is a solid color, the same as your terminal background color. Hopefully, that makes sense.

**Comment by Airblader** [comment]
> Hopefully, that makes sense.

Yeah, it does, thanks for the screenshot. :-)

>  and now that I think about it, it should really just exist as a separate fork. 

I want to give this some more thought, I'm currently on the fence about it.

**Comment by Airblader** [comment]
I've reconsidered and I think I currently don't want this in i3-gaps because I think it's too specific. Of course if other people would want to use this, please make yourself known here.
