### ISSUE TITLE
Smooth resize

### ISSUE THREAD

**Issue by EvilPudding** [Airblader/i3#95]
I know, pointless but pretty, which seems to be the philosophy of this fork, so bare with me.

Is there already a way to achieve this? The only way I noticed is by calling resize several times, a method that seems very inefficient because it redraws the windows at every step. Is there anyway to just redraw the window at the end of shrinking, and beginning of the stretching animation?

I think the result would be both fast and pretty, something to attract users who like that sort of thing (like me when I'm in the mood).

**Comment by Airblader** [comment]
Sorry, I don't really follow. You want to animate resizing, but you _don't_ want to redraw at steps in between? Also, resizing tiled windows already doesn't resize the window until the resize operation is committed.

**Comment by EvilPudding** [comment]
I want to redraw the buffer, I don't want the window's resize events to be called, only at the end of all the shrinking steps and at the beginning of all the stretching steps. What happens currently is that, resize events are called in all the steps, making , for example, all of the widgets in a gtk window adapt to the new size, which is really slow. I want there to be the same number of updates as if it would have been just one resize command, but I want the buffer to redraw in all of the steps, making it smooth.

**Comment by EvilPudding** [comment]
Basically, just warn the window of the resize once the animation is finished (for shrinking) and pretending it's already resized to a larger size (for stretching). Don't know if I'm explaining it too well.

**Comment by EvilPudding** [comment]
If this were implemented, I would use it for both plain window resizing, border resizing, and if possible but far more complicated, window opening transition, where i3 would have to determine the size the window would take, spawn it with size 0 (but drawing a buffer as if it had full size) in the direction of the split, and then animate it to grow while the other splits would shrink. Don't know if you're getting my point, but in my mind it looks good.

**Comment by EvilPudding** [comment]
Another way, less pretty but fine, would be to stretch the buffer while the animation was happening, which would allow the user to extend the animation as long as he wanted, and when he didn't want to resize anymore, i3 would step drawing that distorted buffer, and draw the actual window.

**Comment by Airblader** [comment]
> I don't want the window's resize events to be called

They aren't. For tiled windows, anyway. Floating windows are handled differently. You seem to be describing behavior that doesn't exist, so I'm still confused. We _are_ talking about resizing with the cursor, are we not?

Either way, I don't really see this happening in i3-gaps. My _main_ focus of this fork is to keep it up to date with upstream, which is why I avoid larger changes. This seems like it would be one. At the very least I would suggest suggesting resize behavior changes upstream first.

**Comment by EvilPudding** [comment]
Sorry for not specifying, I was talking about keyboard shortcut resizing. If I want to make it smooth, I have to chain i3 resize commands with smaller steps, so i3 will redraw at every step.

**Comment by Airblader** [comment]
How is i3 supposed to know at which point you are done resizing?

**Comment by EvilPudding** [comment]
For one, I would be happy if it was just an extra argument on the resizing command, which would specify the number of steps it would take to complete that resize, so for example, you want to resize 50px in 10 steps, there would be 10 redraws of the buffer incrementing 10px each. This method would allow i3 to know what the final size of the window would be, so it could, for growing, send down the resize events for the full size. So basically, it would work like a normal resize for the windows, only the borders would take some steps to catch up with the window size.

The other way would be for the user to keep pressing the keys, which would mean i3 wouldn't know the final size, meaning that for growing, i3 would have to either not draw until the user released the keys, or draw a stretching, distorted buffer. Meaning every time a resize command was called, the original resize event would have to be updated instead of creating a new one (this would be far more complicated, and maybe, because I am not so familiar with the system, impossible).

**Comment by Airblader** [comment]
The first suggestion would mean i3 implements animation, the second one is simply impossible because for i3, `resize` is a command that gets sent via the IPC – it doesn't know whether this happened during a keypress or not.

Sorry, I really don't see anything here that is feasible for i3-gaps or stands a chance at being implemented in i3. I also just don't see the usecase. Why artificially make resizing take longer than it has to?

**Comment by EvilPudding** [comment]
Do you think anyone using gaps isn't just wasting screen space?

I know some users might use them for visibility, but that could easily be achieved with plain borders, with the added advantage that borders give information as to what window is focused, why would you sacrifice border space to see more background?
I think most users use it because it's pretty and feels good, many also use it to have space for compton's shadows, others just to remember they still have a background.

I for one am aware I'm wasting screen space for aesthetics, and I don't mind.
Many demonstrations I have seen trying to show off to convince people to switch to linux in general, try to use smooth effects like opacity transitions and such, I understand these are achieved by a compositor, but for resizing it wouldn't be possible, that's why I raised the issue here.

I understand if you don't want it, it was just a thought, something I would find pleasing.

**Comment by Airblader** [comment]
> Do you think anyone using gaps isn't just wasting screen space?

No, I don't.

> but that could easily be achieved with plain borders

No, it can't. Using borders would cause the distance between two windows to be double of what the distance between window and screen edge is.

> why would you sacrifice border space to see more background?

Because it creates the illusion of tiles with gaps, which can feel more organized.

In principle I would love for i3 to be "super fancy looking" and to some extents I'm adding this, if necessary to i3-gaps only. But my _first and foremost_ goal is to keep i3-gaps maintainable with upstream. Large changes would turn i3-gaps into a completely separate project.

As for upstream: we simply do not have the manpower to turn i3 into this kind of window manager. If you want fancy graphics, you'll have to go with one of the larger vendors (KDE, …). It's always easy to propose large changes. It might even be possible to implement large changes. But when 1–2 people have to support and maintain all these changes dozens of people make over time, the project dies a slow and painful death as the number of open issues increases and increases. Unfortunately, people are generally not willing to stick with a project long-term to maintain the changes they contribute.

**Comment by EvilPudding** [comment]
I understand, respect the decision, and will stick with i3. It would be much more work transforming KDE into a more powerful i3 than i3 into a more powerful i3 though.
