### ISSUE TITLE
Resize mode freezes.

### ISSUE THREAD

**Issue by R0flcopt3r** [Airblader/i3#97]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12-118-g155f034 (2016-08-03, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-118-g155f034 (2016-08-03, branch "gaps-next") (pid 21101)
Loaded i3 config: /home/roflcopter/.i3/config (Last modified: to. 18. aug. 2016 kl. 18.30 +0200, 5322 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5670976570261504.bz2

**What I did:**

Pressed $mod+r to enter resize mode.

**What I saw:**
Resize grabbed the keys mapped to it. Won't react to mapped keys. Not even ecape. No way of exiting without killing i3wm from a different session.

**What I expected instead:**
I expected that the resize mode functioned like normal.

**Note**
Using Ubuntu 16.04. There was a lot of troubles installing i3-gaps, a lot of missing dependencies. I did not keep track of the ones missing from the documentations provided by you.

**Comment by Airblader** [comment]
> There was a lot of troubles installing i3-gaps, a lot of missing dependencies. I did not keep track of the ones missing from the documentations provided by you.

That's why you should use a package (PPA) and not compile yourself. Of course somebody has to provide such a package. :-) By the way: i3-gaps doesn't have any dependencies that i3 doesn't.

Anyhow. i3-gaps doesn't modify bindings, binding modes or resizing at all, so please reproduce this bug with the current HEAD of vanilla i3 and report the bug upstream if it persists. Please really do test the current HEAD since we did have problems with numlock.
